"""add version to reference rate and ir monthly cells

Revision ID: 0efeba53be5f
Revises: 7ace0c07f7eb
Create Date: 2026-09-17 08:50:45.545053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0efeba53be5f'
down_revision = '7ace0c07f7eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # server_default so any rows already present (e.g. from earlier partial
    # phases) get version=1 instead of failing the NOT NULL constraint; the
    # default is dropped right after so future inserts must set it explicitly
    # via the ORM (which always does, via the model's `default=1`).
    op.add_column('ir_monthly_revenue', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('reference_rate_monthly_values', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.alter_column('ir_monthly_revenue', 'version', server_default=None)
    op.alter_column('reference_rate_monthly_values', 'version', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reference_rate_monthly_values', 'version')
    op.drop_column('ir_monthly_revenue', 'version')
    # ### end Alembic commands ###
