"""add version to ir_jobs and contracts_projects

Revision ID: 1b44798ef647
Revises: b480be34d7e3
Create Date: 2026-09-17 09:11:11.195785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b44798ef647'
down_revision = 'b480be34d7e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('contracts_projects', sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('contracts_projects', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key(None, 'contracts_projects', 'users', ['updated_by'], ['id'])
    op.add_column('ir_jobs', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.alter_column('contracts_projects', 'version', server_default=None)
    op.alter_column('ir_jobs', 'version', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ir_jobs', 'version')
    op.drop_constraint(None, 'contracts_projects', type_='foreignkey')
    op.drop_column('contracts_projects', 'version')
    op.drop_column('contracts_projects', 'updated_by')
    # ### end Alembic commands ###
