"""initial schema

Revision ID: abd3f5da62d6
Revises: 
Create Date: 2026-09-17 08:36:50.365131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abd3f5da62d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_items',
    sa.Column('group_key', sa.String(length=20), nullable=False),
    sa.Column('item_key', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_key')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sso_subject', sa.String(length=255), nullable=True),
    sa.Column('must_reset_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sso_subject')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.String(length=100), nullable=False),
    sa.Column('field', sa.String(length=150), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_module_record', 'audit_logs', ['module', 'record_id'], unique=False)
    op.create_index('ix_audit_ts', 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_user_ts', 'audit_logs', ['user_id', 'timestamp'], unique=False)
    op.create_table('backups_metadata',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bonds',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('first_fee_date', sa.Date(), nullable=True),
    sa.Column('pay_freq_months', sa.Integer(), nullable=False),
    sa.Column('xhtn', sa.String(length=50), nullable=True),
    sa.Column('par_value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonds_code'), 'bonds', ['code'], unique=True)
    op.create_table('contracts_projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equity_monthly_values',
    sa.Column('month_key', sa.String(length=7), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month_key')
    )
    op.create_table('ir_jobs',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference_rates',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('rate_type', sa.String(length=20), nullable=False),
    sa.Column('calc_method', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('bond_fee_configs',
    sa.Column('bond_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('fee_type_key', sa.String(length=30), nullable=False),
    sa.Column('default_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('recognition_month', sa.String(length=7), nullable=True),
    sa.Column('freq_months', sa.Integer(), nullable=False),
    sa.Column('timing', sa.String(length=10), nullable=False),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['bond_id'], ['bonds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bond_id', 'fee_type_key', name='uq_bond_fee_type')
    )
    op.create_table('bond_interest_config',
    sa.Column('bond_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('rate_type', sa.String(length=20), nullable=False),
    sa.Column('fixed_rate', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('spread', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('reference_rate_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('first4_rate', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('floor_rate', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('cap_rate', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['bond_id'], ['bonds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reference_rate_id'], ['reference_rates.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bond_id')
    )
    op.create_table('bond_monthly_data',
    sa.Column('bond_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('month_key', sa.String(length=7), nullable=False),
    sa.Column('advised_volume', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('buyback_volume', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('invested_volume', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('sold_volume', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('hold_start_override', sa.Date(), nullable=True),
    sa.Column('hold_end_override', sa.Date(), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bond_id'], ['bonds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bond_id', 'month_key', name='uq_bond_month')
    )
    op.create_table('compliance_checklist_entries',
    sa.Column('bond_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('compliance_item_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('month_key', sa.String(length=7), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('assignee_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bond_id'], ['bonds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['compliance_item_id'], ['compliance_items.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_compliance_bond_month', 'compliance_checklist_entries', ['bond_id', 'month_key'], unique=False)
    op.create_index('ix_compliance_item_month', 'compliance_checklist_entries', ['compliance_item_id', 'month_key'], unique=False)
    op.create_table('contracts',
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('contract_date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('parties', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['contracts_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ir_monthly_revenue',
    sa.Column('ir_job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('month_key', sa.String(length=7), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['ir_job_id'], ['ir_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ir_job_id', 'month_key', name='uq_ir_job_month')
    )
    op.create_table('reference_rate_components',
    sa.Column('reference_rate_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('component_rate_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['component_rate_id'], ['reference_rates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reference_rate_id'], ['reference_rates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_rate_id', 'component_rate_id', name='uq_ref_rate_component')
    )
    op.create_table('reference_rate_monthly_values',
    sa.Column('reference_rate_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('month_key', sa.String(length=7), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['reference_rate_id'], ['reference_rates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_rate_id', 'month_key', name='uq_ref_rate_month')
    )
    op.create_table('weekly_portfolio_values',
    sa.Column('bond_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('week_key', sa.String(length=10), nullable=False),
    sa.Column('volume', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('updated_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['bond_id'], ['bonds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bond_id', 'week_key', name='uq_weekly_bond_week')
    )
    op.create_table('bond_fee_rate_periods',
    sa.Column('bond_fee_config_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('fee_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('calculation_method', sa.String(length=10), nullable=True),
    sa.Column('created_by', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['bond_fee_config_id'], ['bond_fee_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bond_fee_rate_periods')
    op.drop_table('weekly_portfolio_values')
    op.drop_table('reference_rate_monthly_values')
    op.drop_table('reference_rate_components')
    op.drop_table('ir_monthly_revenue')
    op.drop_table('contracts')
    op.drop_index('ix_compliance_item_month', table_name='compliance_checklist_entries')
    op.drop_index('ix_compliance_bond_month', table_name='compliance_checklist_entries')
    op.drop_table('compliance_checklist_entries')
    op.drop_table('bond_monthly_data')
    op.drop_table('bond_interest_config')
    op.drop_table('bond_fee_configs')
    op.drop_table('user_roles')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('reference_rates')
    op.drop_table('ir_jobs')
    op.drop_table('equity_monthly_values')
    op.drop_table('contracts_projects')
    op.drop_index(op.f('ix_bonds_code'), table_name='bonds')
    op.drop_table('bonds')
    op.drop_table('backups_metadata')
    op.drop_index('ix_audit_user_ts', table_name='audit_logs')
    op.drop_index('ix_audit_ts', table_name='audit_logs')
    op.drop_index('ix_audit_module_record', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('compliance_items')
    # ### end Alembic commands ###
