"""add timestamps to bond_fee_configs

Revision ID: b480be34d7e3
Revises: c334cd47f7a1
Create Date: 2026-09-17 09:03:34.395272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b480be34d7e3'
down_revision = 'c334cd47f7a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('bond_fee_configs', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.add_column('bond_fee_configs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.alter_column('bond_fee_configs', 'created_at', server_default=None)
    op.alter_column('bond_fee_configs', 'updated_at', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bond_fee_configs', 'updated_at')
    op.drop_column('bond_fee_configs', 'created_at')
    # ### end Alembic commands ###
