"""add version to reference_rates

Revision ID: c334cd47f7a1
Revises: 0efeba53be5f
Create Date: 2026-09-17 08:51:08.714820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c334cd47f7a1'
down_revision = '0efeba53be5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column('reference_rates', sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
    op.alter_column('reference_rates', 'version', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reference_rates', 'version')
    # ### end Alembic commands ###
